name: Upload library to jFrog artifactory

on:
  # For now this upload action will run on feature branches,
  # But once it's working as expected, it will be removed to only run on master pushes
  pull_request:
  push:
    branches:
      - master

jobs:
  upload:
    name: Upload lib to artifactory
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/checkout@v2
      - name: build lib
        run: |
          npm install
          npm run build

      - name: install jfrog
        run: curl -fL https://getcli.jfrog.io | sh

      - name : debug output env values
        run: |
          echo $ARTIFACTORY_URL
          echo "$ARTIFACTORY_URL"
          echo ${{ github.run_id }}

      - name: upload to jfrog
        run: ./jfrog rt config --url "$ARTIFACTORY_URL" --user "$ARTIFACTORY_USER" --password "$ARTIFACTORY_PASSWORD" --interactive=false &&
          ./jfrog rt npmi --build-name=GithubActions --build-number=${{ github.run_id }} "$ARTIFACTORY_NAME" &&
          ./jfrog rt npmp --build-name=GithubActions --build-number=${{ github.run_id }} "$ARTIFACTORY_NAME"